### PR TITLE
PCHR-3542: Custom Group Updates

### PR DESCRIPTION
**Pull request by ajesamson**
This PR merges updates to `Custom Group Updates` implementation to staging.

Included tickets are:

Ticket No. | PRs 
------ | ---- 
PCHR-3599 | [#2798](https://github.com/compucorp/civihr/pull/2798)
PCHR-3600 | [#2801](https://github.com/compucorp/civihr/pull/2801)
PCHR-3624 | [#2797](https://github.com/compucorp/civihr/pull/2797)

### CODE REVIEW

**Comment by mickadoo** [comment]
Why is PCHR-3636 listed in the description? I think that was a separate ticket

**Comment by ajesamson** [comment]
It was part of the previously [reverted PR|https://github.com/compucorp/civihr/pull/2765] so i thought it should also be included. What do you suggest?

**Comment by mickadoo** [comment]
Good point, although I think since those changes weren't reverted (or at least I don't see them in this PR) then it doesn't make sense to mention them in the description.

**Comment by ajesamson** [comment]
Great 👌. PR description has been updated.

**Pull request merged**
